# Generated by Django 2.2.5 on 2019-09-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ids', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SerialNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('ser_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SerialNo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_status', models.IntegerField(max_length=3)),
                ('order_ids', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Order')),
                ('ser_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SerialNo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Status')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ser_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SerialNo'),
        ),
    ]
