# Generated by Django 2.2.5 on 2019-09-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_status',
            field=models.IntegerField(),
        ),
    ]
