# Generated by Django 2.2.5 on 2019-10-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190923_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('ser_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SerialNo')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ser_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SerialNo'),
        ),
        migrations.AlterField(
            model_name='status',
            name='ser_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SerialNo'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
